### ISSUE TITLE
addons21\1776869150\feedback.py:102:to avoid memory leaks, pass an appropriate parent to progress.timer() or use progress.single_shot()

### ISSUE THREAD

**Issue by khonkhortisan** [glutanimate/hitmarkers#7]
```
addons21\1776869150\feedback.py:102:to avoid memory leaks, pass an appropriate parent to progress.timer() or use progress.single_shot()
```
https://github.com/glutanimate/hitmarkers/blob/faaa6c3cf561cb50dc35af93fe34cb28e817a30f/src/hitmarkers/feedback.py#L102-L104

 - OS: Windows 10
 - Anki Version 2.1.55 (35431c59)⁩

**Comment by glutanimate** [comment]
Thanks for the report! This should be fixed with [v0.2.0](https://github.com/glutanimate/hitmarkers/releases/tag/v0.2.0) (which also adds support for Anki 23.x). If you could give it a try and let me know if it works for you I'd appreciate it!
